services:
  backend:
    image: manthan2429/seo-backend:latest
    container_name: seo-backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend/data:/app/data
    restart: always

  frontend:
    image: manthan2429/seo-frontend:latest
    container_name: seo-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: always
